/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hjrvtzkktodoxigezxqy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqcnZ0emtrdG9kb3hpZ2V6eHF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5MzQ1NTAsImV4cCI6MjA4MTUxMDU1MH0.3tr_g_z47Di-Qq-hZLoNsvrFelr2ssCpy6zWHd9IyF4"